### ISSUE TITLE
Safely logging out?

### ISSUE THREAD

**Issue by mpdude** [aws-actions/amazon-ecr-login#160]
I'd like to use GitHub Actions in a way where I would need to pull an image from a private ECR repository, but run untrusted code on the action worker afterwards.

What steps should I take to make sure malicious code can not obtain (temporary) access credentials to ECR? 

Is using `docker logout` enough, or which cleanup steps should I take?

**Comment by asaf400** [comment]
Not sure about the state of the repo on the date you posted,
But right now on main, there's this option:
https://github.com/aws-actions/amazon-ecr-login/blob/cad9b9ce1d5b06e60ee95d1240e6cf3d69074b32/action.yml#L35
and https://github.com/aws-actions/amazon-ecr-login/blob/cad9b9ce1d5b06e60ee95d1240e6cf3d69074b32/action.yml#L13

by default, after the job is done, it cleans up after itself, which is inefficient on mono repo github actions,
Where trying to reuse the ecr login globally between jobs doesn't work because of the explicit logout:
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job

**Comment by mpdude** [comment]
Yes, indeed it logs out once the workflow is finished (after all steps). What I am looking for is a way to make this happen earlier. 

Assume I need to run untrusted `npm` install scripts in a later step of the workflow. Then it would be cautious to remove as many logins/credentials as possible before doing that.

**Comment by mpdude** [comment]
Has this been implemented?
